// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_d-YisIv-yrQ18r9uEaFfbrzNu4nx2Y',
    appId: '1:555382338219:web:4f0bbbebd6fe9ced4d7dee',
    messagingSenderId: '555382338219',
    projectId: 'bee-learn',
    authDomain: 'academy.usebeelearn.com',
    storageBucket: 'bee-learn.appspot.com',
    measurementId: 'G-VPL3JN01D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNoa1tIYB4wxos9RrsFEBsZJHc1gwgWHs',
    appId: '1:555382338219:android:fb54ddba50113ff54d7dee',
    messagingSenderId: '555382338219',
    projectId: 'bee-learn',
    storageBucket: 'bee-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACYXTz2pWcn3mREJgXgVELzqLNjMPVy8M',
    appId: '1:555382338219:ios:a874fe1a7148d7154d7dee',
    messagingSenderId: '555382338219',
    projectId: 'bee-learn',
    storageBucket: 'bee-learn.appspot.com',
    iosClientId: '555382338219-clu4s86ik7ed1n9o5rqsjanjcssq1rik.apps.googleusercontent.com',
    iosBundleId: 'com.oasis.beelearn.beelearn',
  );
}
