name: Deploy to Firebase Hosting on Push
'on':
  push:
    branches:
      - main
jobs:
  build_web_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: sh ./scripts/build-web.bat
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEE_LEARN }}'
          channelId: live
          projectId: bee-learn
